GET http://localhost:3000/products

###create product
POST https://dry-cliffs-94427.herokuapp.com/products
Content-Type:  application/json

{
    "name":"sumil jain",
    "price":180
}

###get a product by id
GET http://localhost:3000/products/id

###update a product by id
PATCH http://localhost:3000/products/id

###delete a product by id
DELETE  http://localhost:3000/products/id

###error route

GET http://localhost:3000/productsdsfdsf
